let result = {
	grid: [
		["t", "b", "e", "s", "t", "e", "l", "l", "e", "n"],
		["l", "b", "i", "m", "n", "s", "i", "", "", ""],
		["i", "p", "c", "h", "a", "i", "r", "m", "a", "n"],
		["u", "h", "a", "t", "e", "m", "p", "l", "e", "s"],
		["q", "p", "l", "y", "", "e", "a", "s", "e", "e"],
		["", "a", "c", "h", "i", "d", "i", "o", "t", "s"],
		["f", "h", "r", "r", "g", "b", "h", "", "", "p"],
		["u", "a", "u", "i", "d", "i", "a", "p", "e", "r"],
		["s", "r", "e", "d", "n", "e", "l", "b", "", "i"],
		["s", "e", "l", "p", "i", "r", "t", "t", "y", "t"],
	],
	insertedWords: [
		"quilt",
		"temples",
		"hoes",
		"rhythms",
		"diaper",
		"blenders",
		"chairman",
		"demise",
		"lacie",
		"iraq",
		"hare",
		"idiots",
		"april",
		"triples",
		"fuss",
		"bestellen",
		"spins",
		"esprit",
		"phpbb",
		"cruel",
		"baby",
		"gilt",
	],
}
