[(0, 8), (0, 9), (1, 0), (3, 7), (5, 0), (5, 2)]
[
    ["y", "i", "s", "e", "n", "d", "h", "f", "y", "s"],
    ["l", "e", "t", "r", "a", "c", "t", "o", "a", "d"],
    ["l", "e", "i", "t", "i", "s", "u", "o", "r", "n"],
    ["e", "m", "m", "a", "r", "g", "o", "r", "p", "u"],
    ["n", "e", "d", "e", "t", "s", "s", "p", "s", "o"],
    ["n", "r", "a", "h", "s", "h", "l", "b", "a", "r"],
    ["o", "g", "n", "t", "e", "o", "l", "a", "d", "r"],
    ["d", "i", "i", "l", "d", "v", "e", "s", "o", "u"],
    ["g", "n", "k", "m", "e", "e", "b", "i", "p", "s"],
    ["u", "g", "i", "m", "p", "l", "a", "n", "t", "s"],
][
    "programme",
    "adopt",
    "surrounds",
    "bellsouth",
    "pedestrian",
    "gimp",
    "implants",
    "eden",
    "shovel",
    "donnelly",
    "proof",
    "cartel",
    "theatre",
    "emerging",
    "admits",
    "niki",
    "basin",
    "spray",
]
